### ISSUE TITLE
Error using hostname into configuration auth.redis.server in version 2.0

### ISSUE THREAD

**Issue by totojack** [emqtt/emq_auth_redis#13]
Hi.

It seems it's not possible to use hostname into configuration

**auth.redis.server = 127.0.0.1:6379**

I'm trying to use emqtt inside docker compose with a redis service (with name "redis") and if I set for example

**auth.redis.server = redis:6379**

or

**auth.redis.server = "redis":6379**

I've got this error

> emqtt                       | 08:35:15.125 [error] Error generating configuration in phase transform_datatypes
> emqtt                       | 08:35:15.125 [error] Error transforming datatype for: auth.redis.server
> emqtt                       | 08:35:15.125 [error] "\"redis\":6379" cannot be converted to a(n) integer
> emqtt                       | 08:35:15.125 [error] "\"redis\":6379" cannot be converted to a(n) IP

I'm sure that it was possible in previous versions to use something like

> {redis_pool, [
>   %% pool options
>   {pool_size, 8},
>   {auto_reconnect, 2},
> 
>   %% redis options
>   {host, "redis"},
>   {port, 6379},
>   {database, 0},
>   {password, ""}
> ]}.

Thanks
Luca

**Comment by turtleDeng** [comment]
hi
auth.redis.server = 127.0.0.1:6379

**Comment by totojack** [comment]
Hi

So it's not possible to use an hostname

auth.redis.server =  mycustomhostname:6379

We must use an IP. Can you confirm?

Thanks

**Comment by emqplus** [comment]
@totojack, @turtleDeng, I submit a PR: https://github.com/emqtt/emq_auth_redis/pull/14

**Comment by emqplus** [comment]
Merged the PR #14
